name: Go Run & Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.2
      - name: Run
        run: go run main.go
      - name: Test
        run: go test -v
  another-build:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.2
      - name: Run
        run: go run main.go
      - name: Test
        run: go test -v
